# Generated by Django 5.2 on 2025-04-15 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_payments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='amount',
            new_name='price',
        ),
    ]
